version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application --access-logfile -
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A backend worker --loglevel=INFO --pool=solo
    volumes:
      - .:/app
    depends_on:
      - django
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A backend beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - django
      - redis


