# Generated by Django 5.2.12 on 2026-03-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonduser',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='bonduser',
            name='last_name',
        ),
    ]
