# Generated by Django 5.2.12 on 2026-03-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authotp',
            name='is_used',
        ),
    ]
