# Generated by Django 5.2.12 on 2026-03-21 15:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_authotp_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('freemium', 'Freemium'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('has_ads', models.BooleanField(default=True)),
                ('max_accounts', models.IntegerField(default=3)),
                ('folder_sharing', models.BooleanField(default=False)),
                ('password_protected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('tier', 'billing_cycle', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_on', models.DateTimeField()),
                ('cancelled_on', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('snapshot_tier', models.CharField(max_length=20)),
                ('snapshot_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('snapshot_tax_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('snapshot_tax_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('snapshot_total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('snapshot_has_ads', models.BooleanField()),
                ('snapshot_max_accounts', models.IntegerField()),
                ('snapshot_folder_sharing', models.BooleanField()),
                ('snapshot_password_protected', models.BooleanField()),
                ('snapshot_all_future_features', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='account.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on'],
            },
        ),
    ]
