# Generated by Django 5.2.12 on 2026-03-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_country_bonduser_country_state_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonduser',
            name='is_app_user',
            field=models.BooleanField(default=False),
        ),
    ]
