# Generated by Django 5.2.12 on 2026-03-17 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='googledriveaccount',
            name='app_used_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='googledriveaccount',
            name='total_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='googledriveaccount',
            name='user_used_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('local_media_id', models.CharField(help_text='ID from phone gallery', max_length=255)),
                ('device_id', models.CharField(help_text='Originating device ID', max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='IMAGE, VIDEO, etc.', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('remote_id', models.CharField(blank=True, help_text='Cloud file ID', max_length=255, null=True)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='core.folder')),
            ],
        ),
        migrations.DeleteModel(
            name='SyncData',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['content_type', 'object_id'], name='core_file_content_ba630e_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['local_media_id', 'device_id'], name='core_file_local_m_ccb2b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('content_type', 'object_id', 'local_media_id', 'device_id')},
        ),
    ]
