# Generated by Django 5.2.12 on 2026-03-21 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_folders', to='core.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='googledriveaccount',
            name='app_used_storage',
            field=models.BigIntegerField(default=0, help_text='Used storage in bytes'),
        ),
        migrations.AlterField(
            model_name='googledriveaccount',
            name='remaining_storage',
            field=models.BigIntegerField(default=0, help_text='Remaining storage in bytes'),
        ),
        migrations.AlterField(
            model_name='googledriveaccount',
            name='total_storage',
            field=models.BigIntegerField(default=0, help_text='Total storage in bytes'),
        ),
        migrations.AlterField(
            model_name='googledriveaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='googledriveaccount',
            name='user_used_storage',
            field=models.BigIntegerField(default=0, help_text='Used storage in bytes'),
        ),
    ]
